version: '3'
services:
  mariadb:
    image: mariadb/server:10.3
    networks:
      - main-network
    environment:
      MYSQL_ROOT_PASSWORD: 123
    ports:
      - "3306:3306"
  springApplication:
    build:
      dockerfile: ./docker/springApp.dockerfile
      context: .
    image: spring-app
    container_name: springApplication
    ports:
      - "8080:8080"
    depends_on:
     - "mariadb"
    networks:
      - main-network

networks:
  main-network:
    driver: bridge